### ISSUE TITLE
Looks like the matplotlib version is wrong? 1.1.1 vs 1.5.1?

### ISSUE THREAD

**Issue by twhyntie** [OpenCosmics/cosmic-jupyter#1]
So `test.ipynb` is failing with the [HiSPARC tutorial example](http://docs.hisparc.nl/sapphire/tutorial.html)... what's determining that the `matplotlib` version is 1.1.1?

**Comment by tpmccauley** [comment]
@twhyntie is that the version you have? I found that I had to upgrade to at least 1.5.x

**Comment by twhyntie** [comment]
@tpmccauley No, it's the version that shows when I view the notebook in the [browser](https://github.com/OpenCosmics/cosmic-jupyter/blob/master/test.ipynb)... what's powering the backend of this?

**Comment by tpmccauley** [comment]
@twhyntie ah, I see. Nothing is powering it. github just displays notebook results. With errors! I will update (I know I have sinned by pushing to master).

**Comment by twhyntie** [comment]
@tpmccauley Sorry, I badly phrased that. I meant, "_what determines the version of_ `matplotlib` _that github uses to display the notebook results_". From the error messages and the output of `matplotlib.__version__` it looks like `1.1.1`, which I'm guessing is why the `new` keyword argument of `hist` is causing an error...?

**Comment by tpmccauley** [comment]
@twhyntie it's showing the result of my error running on my Mac. So the version of matplotlib is determined by what's on one's machine. Github just displays the text; it doesn't run the notebooks (yet). 

I had 1.1.1 when I ran the notebook and committed. I shouldn't have 1) committed to the master 2) committed when there was an error. Mea culpa. But in the heat of the sprint...

Anyway, I have updated it and you should see it ran with 1.5.1

**Comment by RaoOfPhysics** [comment]
@tpmccauley: But you committed straight to `master` again… :(

**Comment by tpmccauley** [comment]
@RaoOfPhysics Yes, I know. In for a penny...

**Comment by RaoOfPhysics** [comment]
Looks like I'll have to revoke your privileges. :P <ducks>
